
resolver: lts-16.8
compiler: ghc-8.10.2
# compiler: ghc-8.8.4
# compiler: ghc-8.6.5
allow-newer: true

# resolver: lts-14.0

flags:
  liquid-fixpoint:
    devel: true 

packages:
- ../../rewriting-paper/formalization/haskell
- '.'


extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- tasty-rerun-1.1.14
